name: nadfact2
description: "mobile app for NadFact"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  http: ^1.2.1
  intl: ^0.17.0
  visibility_detector: ^0.2.0
  shared_preferences: ^2.0.6
  web_socket_channel: ^2.1.0
  stomp_dart_client: ^1.0.0
  cupertino_icons: ^1.0.8
  scrollable_positioned_list: ^0.3.8
  video_player: ^2.9.1

  get: ^4.6.6
  hexcolor: ^3.0.1
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  flutter_pdfview: ^1.3.2
  path: ^1.9.0
  dio: ^5.6.0
  file_utils: ^1.0.1
  permission_handler: ^11.3.1
  file_picker: ^8.1.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logovid.mp4
